; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 921600 

lib_extra_dirs = ../Tag_Serial_two_tags/lib

[env:anchor0]
build_flags = -D ANCHOR_ID=0

[env:anchor1]
build_flags = -D ANCHOR_ID=1

[env:anchor2]
build_flags = -D ANCHOR_ID=2

[env:anchor3]
build_flags = -D ANCHOR_ID=3

[env:anchor4]
build_flags = -D ANCHOR_ID=4

[env:anchor5]
build_flags = -D ANCHOR_ID=5

[env:anchor6]
build_flags = -D ANCHOR_ID=6

[env:anchor7]
build_flags = -D ANCHOR_ID=7

[env:anchor8]
build_flags = -D ANCHOR_ID=8

[env:anchor9]
build_flags = -D ANCHOR_ID=9
